# syntax=docker/dockerfile:1
FROM golang:1.22-alpine AS builder
WORKDIR /src

# first copy go.mod only to leverage cache when deps don't change
COPY go.mod .
RUN go mod download

# copy the rest of the source
COPY . .

# ensure go.sum is up to date (in case it was missing locally) and deps fetched
RUN go mod tidy

# build binary
RUN go build -o app ./cmd/app

FROM alpine:latest
WORKDIR /app
COPY --from=builder /src/app .
EXPOSE 8080
CMD ["./app"] 